### ISSUE TITLE
Call tips.show() in an asynchronous function 

### ISSUE THREAD

**Issue by dongbohu** [Caged/d3-tip#176]
When I tried to call tip.show() in another asynchronous function like this:
```
tip = d3.tip().attr('class', 'd3-tip').html("Loading...");
vis.call(tip)

vis.selectAll('rect')
  .data(data)
  .enter()
  .append('rect')
  .on('mouseover', show_tip)
  .on('mouseout', tip.hide);

function show_tip(data) {
  $http.get('http://example.com/?query=foobar').success(function(response) {
        result = response;
        edge_tip.html(response);
        edge_tip.show(data);
  });
}
```
I keep getting this error:
```TypeError: Cannot read property 'target' of null```
Any idea why? Thanks.

**Comment by vdh** [comment]
Do you have a working example of the problem?

**Comment by dongbohu** [comment]
Thank you very much for your reply. I will create a simple example and post the code here.

**Comment by dongbohu** [comment]
Attached is an example that was based on the d3 bar chart at http://bl.ocks.org/Caged/6476579. I converted it into a AngularJS app. The most import changes are: 
line 66: 
```.on('mouseover', show_tip)```
and lines 76-80, which calls **tip.show()** in asynchronously:
```
       function show_tip(d) {
             $timeout(function() {
                 tip.show(d);
             }, 100);
       }
```

[tip.html.gz](https://github.com/Caged/d3-tip/files/516947/tip.html.gz)
Thanks again.

**Comment by dongbohu** [comment]
Here is the same example w/o using AngularJS. It calls **setTimeout()** instead.
[set_timeout.html.gz](https://github.com/Caged/d3-tip/files/517018/set_timeout.html.gz)

**Comment by vdh** [comment]
So you're using the 0.6.x branch?

**Comment by vdh** [comment]
It looks like the async call is losing the relevant `d3.event.target`, so you have to store it before calling your async code, then pass it in as the last argument to `tip.show`:

```js
// ...
.on('mouseover', function(d) {
  var target = d3.event.target;
  doAsync()
    .then(function() {
      tip.show(d, target);
    });
})

function doAsync() {
  return new Promise(function (resolve) {
    setTimeout(function() {
      resolve();
    }, 100);
  });
}
```
Or since you're already using Angular, you can use the Promise returned from `$http` or `$timeout`:

```js
vis.selectAll('rect')
  .data(data)
  .enter()
  .append('rect')
  .on('mouseover', showTip)
  .on('mouseout', tip.hide);

function showTip(data) {
  var target = d3.event.target;
  $http.get('http://example.com/?query=foobar')
    .then(function(response) {
      // ...
      tip.show(data, target);
    });
}
```

Angular's [`$q` library Promise](https://docs.angularjs.org/api/ng/service/$q) is very similar to the new [ES6 Promise](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise), so I would recommend switching to using the newer Promise methods (`.then` and `.catch`) instead of the older `.success` method 😉

**Comment by dongbohu** [comment]
Thank you very much for your reply. It is very helpful!
