### ISSUE TITLE
Tooltip binding to body instead of svg rect

### ISSUE THREAD

**Issue by phil-dileo** [Caged/d3-tip#183]
Hi - I'm using d3-tip in a react project and having an issue with where the tooltip binds to. I'm using it like so:

```
"d3": "~3.5.16",
"d3-tip": "~0.6.8",
```

```
import d3 from 'd3';
import tip from 'd3-tip';
...
const svg = d3.select(this.refs.graphContent)
        .attr('width', width)
        .attr('height', height)
        .style('margin-left', MARGIN.left + 'px')
        .attr('transform', translate(MARGIN.left, MARGIN.top));

d3.tip = tip;

const offset = DEFAULT_ROW_HEIGHT / -4;
const tooltip = d3.tip()
  .attr('class', 'data-grid-tooltip')
  .html(d => {
    return `<span>${d.value}</span>`;
   })
   .offset([offset, 0]);

svg.call(tooltip);

const cell = svg.append('rect')
  .attr('transform', translate(X_AXIS_TICK_MARGIN, 0))
  .classed('data-grid-cell', true)
  .attr('x', () => { return xScale(col.name); })
  .attr('y', () => { return yScale(row.name); })
  .attr('width', xScale.rangeBand())
  .attr('height', yScale.rangeBand());

cell.on('mouseover', function show() {
  if (_.has(cellData, 'value')) {
    d3.select(this).classed('data-grid-cell-hover', true);
    tooltip.show(cellData);
  }
})
.on('mouseout', function hide() {
  if (_.has(cellData, 'value')) {
    d3.select(this).classed('data-grid-cell-hover', false);
    tooltip.hide(cellData);
  }
});

cell.transition()
  .duration(TRANSITION_DURATION_COMMON)
  .delay(() => { return _.random(20, 500); })
  .ease('linear')
  .style('fill', cellData.color);
}
```

The tooltip always binds to the body element.  Also, if I mouseover, the tooltip is displayed, but then if I scroll the tooltip just floats in the same position on page instead of sticking with the rect.  Any tips?  I know the invocation of `tip` is not normal, but that's the only way I could get it to work. Thanks

**Comment by cjhin** [comment]
Also having this exact same issue, d3-tip react is binding the tooltips to the `<body>`.

I have a feeling this issue request will never get resolved though given the state of this repo...

**Comment by Caged** [comment]
@cjhin passive-aggressive comment aside, if you'd like to help fix this you could provide a simple-as-possible working example of the problem.  It's difficult to debug partial code blocks in GitHub comments.

**Comment by cjhin** [comment]
@Caged ahhhhh sorry sorry sorry you're right that comment was very rude of me and out of line, I apologize.  I was under the impression the repo was no longer being maintained due to issue request #154 (<-- this is the sentence I should've written instead).

Unfortunately the code base I'm having this issue in is rather large, but I'll see if I can create a demo/toy example to replicate the issue.

**Comment by phil-dileo** [comment]
I think I found the issue (for my case).  The logic inside this tool accommodates for the screen top/left position as well as any scrolling offsets.  The problems is that my application scrolls within an inner frame, not the main body, so the offsets never get updated.  I ended up just implementing a simple D3 text tooltip.  Thanks!

**Comment by vdh** [comment]
@phil-dileo That sounds similar to the issue I encountered with #175. Unfortunately that stalled because I didn't know enough about the use case of the introduced `rootElement` feature to fix the scrolling issue. That and I unfortunately don't have much free time to dedicate to working on code these days.
