### ISSUE TITLE
LineChart mouseout behavior is goofed up

### ISSUE THREAD

**Issue by wjaspers** [Caged/d3-tip#73]
I think this may actually be a problem with DC-js, but I've discovered you need to use 'mouseleave' instead of 'mouseout' when working with a line chart, or the pointer axes are left on-screen.

**Comment by gordonwoodhull** [comment]
I know this is ancient, but in case anyone runs into this, the issue is almost certainly that dc.js is not properly namespacing all of its event handlers (dc-js/dc.js#842). 

But you should always namespace your event handlers too!

So invoke d3.tip like this

```js
            .on("mouseover.some-unique-id", tip.show)
            .on("mouseout.some-unique-id", tip.hide)
```

and then dc.js won't overwrite your event handlers.
