### ISSUE TITLE
Tooltips won't hide

### ISSUE THREAD

**Issue by Phisherman** [Caged/d3-tip#87]
Hi,

My problem is that sometimes the tooltips won't hide. I use DC.js to build the graphs.

![image](https://cloud.githubusercontent.com/assets/2873986/4991346/ab4d55f2-6992-11e4-8237-04f8d00d9ed7.png)

The tooltips won't hide, when you click in the graph, wait for at least ~0.5s and then leave it. I logged the mouseout in the console. And it raised the event properly.

**Comment by tlrobinson** [comment]
I still see this behavior even if I use `mouseleave`, I think due to the way my charts get re-rendered when I click them. The old chart is discarded but the tooltip remains behind. It would be nice if d3-tip was smart enough to delete orphaned tooltips, but I'm not sure what the correct way to do that is.

One possible workaround is to delete any old tooltip nodes when the chart is rendered:

```
Array.prototype.forEach.call(document.querySelectorAll('.d3-tip'), (t) => t.parentNode.removeChild(t));
```

**Comment by breakingco** [comment]
This happens to me, too. I am needing to use a single instantiation of tip() per tip because I have a separate html template I am interpolating using angular $interpolate for every different tip (this was done because it was getting super messy and repetitive to build context-sensitive html tips in javascript  for every possibility using '<div>+d.blah+'</div>' etc - if anyone has a more elegant way of doing this I'd be all ears).

What happens then since I have about 50 tips at any time, is that as I switch between graphs I end up with hundreds appended to the body. The nearest I can get to removing them is as above, deleting them all whenever I destroy a graph or registering callbacks to destroy each tip....but seconded if this was done automatically, that would be great...

**Comment by ethanyu123** [comment]
Hey, guys.  I encountered the same problem, _cause I changed opacity._ 

And the problem's gone when I remove it. 

FYI

**Comment by Caged** [comment]
This appears resolved or underspecified.
